In [1]:
import numpy as np

In [9]:
a = np.arange(9).reshape(3, 3)
b = np.arange(3).reshape(3, 1)
c = np.dot(a, b)
d = np.array([1])
c + d

array([[ 6],
       [15],
       [24]])

In [3]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
b = np.array([2, 3, 4])
b

array([2, 3, 4])

In [5]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [6]:
a * b

array([[ 0,  3,  8],
       [ 6, 12, 20],
       [12, 21, 32]])

In [11]:
x = np.array([1, 2, 3]).reshape(3, 1)
y = np.array([2, 3, 4]).reshape(1, 3)
print(x)
print(y)

[[1]
 [2]
 [3]]
[[2 3 4]]


In [12]:
x * y

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])

In [9]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
y*x

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])

In [10]:
b

array([2, 3, 4])

In [13]:
c = np.arange(10).reshape(-1, 1)

In [14]:
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [16]:
c.sum(axis=0)
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [18]:
hello = c.sum(axis=0)

In [21]:
hello.shape

(1,)

In [2]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
a = a.sum(axis=0)

In [7]:
a.shape

(3,)

In [11]:
a.sum(axis=0).shape

()

In [12]:
np.arange(-3, 3, .01)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('a+b:', a+b)
print('a-b:', a-b)
print('a*b:', a*b)
print('a/b:', a/b)

a+b: [5 7 9]
a-b: [-3 -3 -3]
a*b: [ 4 10 18]
a/b: [0.25 0.4  0.5 ]


In [16]:
a = np.arange(12).reshape(3, 4)
print(a)
print()
print('a.sum(axis=0) ', a.sum(axis=0))
print('a.sum(axis=1) ', a.sum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a.sum(axis=0)  [12 15 18 21]
a.sum(axis=1)  [ 6 22 38]


In [18]:
a = np.arange(12).reshape(3, 4)
b = np.arange(12).reshape(4, 3)
print('a: ', a)
print()
print('b: ', b)
print(a + b)

a:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

b:  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [36]:
a = np.arange(9).reshape(9,1)
print(a)
print()

b = np.transpose(a, (1, 0))
# b = np.transpose(a)
print(b)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

[[0 1 2 3 4 5 6 7 8]]
